### ISSUE TITLE
Does it really need PHP 7.1 to run?

### ISSUE THREAD

**Issue by bcalik** [tomgrohl/laravel4-php71-encrypter#1]
I want my project to be run on both PHP 5.6 and newer versions of php, but this package requires PHP 7.1. Does it really necessary?

**Edit:** Or at least it should run on PHP 7.0.

**Comment by tomgrohl** [comment]
I originally wrote it for PHP 7.1 because that ships with Laravel would work up to PHP 7.0.

There are a few bits that reply on PHP 7. e.g random_bytes but looks like theres a polyfill for that [here](https://github.com/paragonie/random_compat).

It would be possible to make it work with PHP 5.6+, that way your application can run with this one and then you should be able to upgrade PHP with few issues.

I'll get this sorted for the next release.

**Comment by tomgrohl** [comment]
Version 1.1.0 has been released making it possible to run for PHP 5.6+
