### ISSUE TITLE
README change

### ISSUE THREAD

**Issue by anthonycmain** [tomgrohl/laravel4-php71-encrypter#13]
If you use the composer statement

composer require tomgrohl/laravel4-php71-encrypter

You get the 2.0@dev version which causes the error below as reported by @hugossvoboda in this ticket, which you have quite rightly answer.

> issue in Cookie\Guard::__construct() after complete all steps

https://github.com/tomgrohl/laravel4-php71-encrypter/issues/12

May I suggest changing the line this, to avoid this issue in the future

composer require tomgrohl/laravel4-php71-encrypter:1.1.*

**Comment by anthonycmain** [comment]
Also I was getting an error with the Provider code and had to use:

'\Tomgrohl\Laravel\Encryption\EncryptionServiceProvider'

rather than 

'\Tomgrohl\Laravel\Encryption\EncryptionServiceProvider:class'

**Comment by tomgrohl** [comment]
Hi

Sorry for the really long delay in replying. 

I've had other commitments and not been working on open source projects for a while now.

The issue was caused by development on the master branch for a new change, which won't actually work because of how Laravel 4 works.

Laravel 4 was also setup to include dev packages, which is a bit silly really, so when people install this package it bypasses the stable version and goes for the in development version.

I've reverted the changes on master so this will no longer be a problem, version 1.1.3 being the only version it can install. I've tested this with an fresh setup and works fine.

Thanks for raising.
