### ISSUE TITLE
Laravel 4.2 using MCRYPT_RIJNDAEL_128 can decrypt session

### ISSUE THREAD

**Issue by ghost** [tomgrohl/laravel4-php71-encrypter#7]
I configured my main app (call it core) which is laravel 4.2 which handles login for all my other apps(also laravel 4.2) too to use the package. 
I realized that the other apps which I had not yet configured to AES-256-CBC were still being able to decrypt the session. 

I am using your package because I wanted to connect a laravel 5.4 app to use the session from the core but it is also not working.

My session is saved in the database.

**Comment by tomgrohl** [comment]
Not sure what you asking. I'm assuming its more about sessions across apps than the encrypter itself. This issue is beyond the scope of this project but I'll try and help.

No matter where the session is stored there is usually a cookie for web logins. Not sure how much the session implementations differ between Laravel versions but as login as the cookie belongs to both apps (domains) the session should work. The cookie would have to belong to the top level domain if you also have apps running on subdomains. You would also have to make sure the cookie name is unique to the app so it doesn't collide.

**Comment by ghost** [comment]
The cookie is set on the top level domain, but when I am accessing the new laravel on the sub domain it redirects to the login page.
But laravel uses the app key to encrypt the cookies also. The other legacy apps are still able to access the cookies and login even though those app haven't been setup to this package but the laravel 5.4 doesn't work

You can't use a base64 key (eg base64:Ppg0SChETMwbuykjt2+IZDiZJ6WOr4UcvGhi5p/9/dU=) returns this error "The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths."
This is key generate from the laravel 5.4 app.
