### ISSUE TITLE
Stop extending Laravel Encrypter which replies on mcrypt variables

### ISSUE THREAD

**Issue by MircoBabin** [tomgrohl/laravel4-php71-encrypter#8]
Commit https://github.com/tomgrohl/laravel4-php71-encrypter/commit/fdc3b4aa8c7965e19d8e08295f78088183c626d7 removes the extending of Laravel Encrypter.

I executed this on a real live situation and got (I really don't understand why, seems like somehow strict_types are enabled globally by the ISP, really strange):

[EDIT] This happens on PHP 7.1.6

![image](https://user-images.githubusercontent.com/8981285/46290874-4f855980-c58d-11e8-83a4-643da0411cf6.png)

**Comment by tomgrohl** [comment]
That commit was done as part of an ongoing job to try and get the Encrypter working with PHP 7.2, but as Laravel requires the Encrypter class and not an interface it turns out it won't work. It it not even part of a stable release so I'm not sure why you've got it installed and running on a live site.

If you make sure your running version 1.1.3 and you'll be fine.
